### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by srirammadduri** [tgrall/couchbase-sql-importer#3]
Hi,

I am getting Error: Could not find or load main class com.couchbase.util.SqlImporter error,

How to resolve this?

**Comment by srirammadduri** [comment]
try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("Where is your MySQL JDBC Driver?");
            e.printStackTrace();
            return;
        }

need this initialization in the main class in SqlImporter.java to work this library

**Comment by bhargavbvs** [comment]
Where to include this? I'm getting the same error.
